import hre from "hardhat";
import fs from "fs";
import path from "path";

async function main() {
    const [deployer, agent, reviewer, juror] = await hre.ethers.getSigners();
    console.log("Using pre‑deployed contracts with the account:", deployer.address);

    // Load deployment addresses generated by scripts/deployAll.js
    const deploymentPath = path.resolve(__dirname, "deployment.json");
    if (!fs.existsSync(deploymentPath)) {
        throw new Error("deployment.json not found. Run `npx hardhat run scripts/deployAll.js --network localhost` first.");
    }
    const deployment = JSON.parse(fs.readFileSync(deploymentPath, "utf8"));

    // Attach to already deployed contracts
    const identityRegistry = await hre.ethers.getContractAt("AgentIdentityRegistry", deployment.identityRegistry);
    const reputationRegistry = await hre.ethers.getContractAt("AgentReputationRegistry", deployment.reputationRegistry);
    const validationRegistry = await hre.ethers.getContractAt("AgentValidationRegistry", deployment.validationRegistry);
    const serviceRegistry = await hre.ethers.getContractAt("AgentServiceRegistry", deployment.serviceRegistry);
    const juryRegistry = await hre.ethers.getContractAt("AgentJuryRegistry", deployment.juryRegistry);

    // ==== Agent Registration ==== 
    console.log("\nRegistering an Agent...");
    const agentUri = "https://example.com/agent-metadata.json";
    const tx = await identityRegistry.registerAgent(agent.address, agentUri);
    await tx.wait();
    const tokenId = await identityRegistry.getAgentTokenId(agent.address);
    console.log(`Agent registered! Token ID: ${tokenId}, Address: ${agent.address}`);

    // ==== Service Registration ==== 
    console.log("\nRegistering a Service...");
    const serviceId = "service-1";
    const serviceMetadata = "https://example.com/service-metadata.json";
    const serviceTx = await serviceRegistry.registerService(tokenId, serviceId, serviceMetadata);
    await serviceTx.wait();
    console.log(`Service registered! Service ID: ${serviceId}`);

    // ==== Task Submission & Validation ==== 
    console.log("\nSubmitting Task with 1 ETH fee...");
    const taskHash = hre.ethers.keccak256(hre.ethers.toUtf8Bytes("Task Result Data"));
    const fee = hre.ethers.parseEther("1.0");
    const taskTx = await validationRegistry.connect(agent).submitTask(tokenId, taskHash, { value: fee });
    await taskTx.wait();
    const taskId = 1; // demo assumes first task ID is 1
    console.log(`Task submitted! Task ID: ${taskId}, Hash: ${taskHash}, Fee: ${hre.ethers.formatEther(fee)} ETH`);

    console.log("Validating Task...");
    const validatorInitialBalance = await hre.ethers.provider.getBalance(reviewer.address);
    const validateTx = await validationRegistry.connect(reviewer).validateTask(taskId, true);
    await validateTx.wait();
    const validatorFinalBalance = await hre.ethers.provider.getBalance(reviewer.address);
    console.log("Task validated!");
    console.log(`Validator balance change: ${hre.ethers.formatEther(validatorFinalBalance - validatorInitialBalance)} ETH`);

    // ==== Reputation ==== 
    console.log("\nAdding Reputation...");
    const score = 95;
    const comment = "Great service, very fast!";
    const repTx = await reputationRegistry.connect(reviewer).addReputation(tokenId, score, comment);
    await repTx.wait();
    console.log("Reputation added!");

    // ==== Juror Registration ==== 
    console.log("\nRegistering a Juror (staking 0.2 ETH)...");
    const stake = hre.ethers.parseEther("0.2");
    const jurorTx = await juryRegistry.connect(juror).registerJuror({ value: stake });
    await jurorTx.wait();
    console.log(`Juror registered! Address: ${juror.address}, Stake: ${hre.ethers.formatEther(stake)} ETH`);

    // ==== Dispute Creation ==== 
    console.log("\nCreating a Dispute on the Task...");
    const disputeFee = hre.ethers.parseEther("0.5");
    const disputeTx = await juryRegistry.connect(juror).createDispute(taskId, { value: disputeFee });
    const receipt = await disputeTx.wait();
    const disputeId = receipt.events?.find(e => e.event === "DisputeCreated")?.args?.disputeId || 1;
    console.log(`Dispute created! Dispute ID: ${disputeId}, Task ID: ${taskId}`);

    // ==== Juror Voting ==== 
    console.log("\nJuror voting on dispute (support = true)...");
    const voteTx = await juryRegistry.connect(juror).vote(disputeId, true);
    await voteTx.wait();
    console.log(`Juror ${juror.address} voted in favor of validity`);

    // ==== Execute Ruling ==== 
    console.log("\nExecuting ruling for dispute...");
    const execTx = await juryRegistry.executeRuling(disputeId);
    await execTx.wait();
    console.log(`Ruling executed for dispute ${disputeId}`);

    // ==== Verify Data ==== 
    console.log("\nVerifying Data...");
    const task = await validationRegistry.getTask(taskId);
    console.log(`Task ${taskId} Status:`);
    console.log(`  Validated: ${task.isValidated}`);
    console.log(`  Valid: ${task.isValid}`);
    console.log(`  Validator: ${task.validator}`);

    const reviews = await reputationRegistry.getReputation(tokenId);
    console.log("Reviews for Agent:", tokenId.toString());
    reviews.forEach((review, index) => {
        console.log(`Review #${index + 1}:`);
        console.log(`  Reviewer: ${review.reviewer}`);
        console.log(`  Score: ${review.score}`);
        console.log(`  Comment: ${review.comment}`);
    });

    const avgScore = await reputationRegistry.getAverageScore(tokenId);
    console.log(`Average Score: ${avgScore}`);

    const services = await serviceRegistry.getAgentServices(tokenId);
    console.log(`\nServices for Agent ${tokenId}:`, services);

    const dispute = await juryRegistry.disputes(disputeId);
    console.log(`\nDispute ${disputeId} details:`);
    console.log(`  Challenger: ${dispute.challenger}`);
    console.log(`  Votes For: ${dispute.votesFor}`);
    console.log(`  Votes Against: ${dispute.votesAgainst}`);
    console.log(`  Resolved: ${dispute.resolved}`);
    console.log(`  Ruling (true=valid): ${dispute.ruling}`);
}

main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});
